#!/bin/sh

mount -t proc proc /proc
mount -t devtmpfs devtmpfs /dev

modprobe ahci
modprobe xts

/scripts/opendmcrypt.sh /dev/sda

DISTRO=gentoo
RELEASE=livedvd-amd64-multilib-20140826
DISTROPATH=distros/$DISTRO-$RELEASE
DISTROLOOP="$DISTROPATH/$RELEASE.iso image.squashfs"

RO_ROOT="$(/scripts/loopdeloop.sh /dev/mapper/data-0 $DISTROLOOP)"
#./loopdeloop.sh /dev/mapper/data-0 Qubes-R2-x86_64-DVD.iso LiveOS/squashfs.img LiveOS/rootfs.img

DISTROPATH="/mnt/image/0/$DISTROPATH"
ROOT="$DISTROPATH"/root

mount -t aufs -o "br:$DISTROPATH/overlay:$RO_ROOT=rr" "$DISTRO-$RELEASE" "$ROOT"

for move in /proc /dev /mnt/image/*; do
	mount --move "$move" "$ROOT$move"
done

echo
echo "Anything you'd like to do before booting?  Exit to continue."
/bin/sh


exec switch_root -c /dev/console "$ROOT" /sbin/init

